import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { fileURLToPath } from "node:url";

export default defineConfig({
  plugins: [react()],
  server: { port: 5173 },
  resolve: {
    alias: {
      // Rollup's parser rejects the published xrpl-connect bundle (valid JS
      // that V8 and esbuild both accept) with "Constructor in/after an
      // optional chaining is not allowed". scripts/vendor-xrpl-connect.mjs
      // re-emits it through esbuild at es2019, and this points the bundler at
      // that output. TypeScript is unaffected: `import from "xrpl-connect"`
      // still resolves its types from node_modules, so the API stays checked.
      // Regenerated by the `prebuild` script, including on Vercel.
      "xrpl-connect": fileURLToPath(new URL("./src/vendor/xrpl-connect.js", import.meta.url)),
    },
  },
});
